// generated by dlavm.backend in 2025-02-24 08:49:32

// runtime storage define
uint64_t runtime0 = 0x000000000;
uint64_t runtime1 = 0x000002710;
// hbm storage define
uint64_t hbm0 = 0x000000000;

uint64_t input = runtime0;

uint64_t output = runtime1;

void weight1_load_param(HANDLE& h2cx, char* prefix) {
  for (int port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/test", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)hbm0), 10000);
  }
}

void test_load_params(HANDLE& h2cx, char* prefix) {
  weight1_load_param(h2cx, prefix);
}

void mvm_step_1(HANDLE& device) {
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, 19);
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, 19);
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 0);
  CSB_Write(device, 9, 0);
  CSB_Write(device, 10, 0);
  CSB_Write(device, 11, 4864);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 275200);
  CSB_Write(device, 14, 0);
  CSB_Write(device, 15, 0);
  CSB_Write(device, 16, 0);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 0);
  CSB_Write(device, 22, 5769216);
  CSB_Write(device, 23, 3670144);
  CSB_Write(device, 24, 2048);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 0);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, 608);
  CSB_Write(device, 30, 608);
  CSB_Write(device, 31, 608);
  CSB_Write(device, 32, 608);
  CSB_Write(device, 33, 15);
  while (CSB_Read(device, 1) != 1) {}
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, 19);
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, 19);
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 1024);
  CSB_Write(device, 9, 0);
  CSB_Write(device, 10, 0);
  CSB_Write(device, 11, 72448);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 276416);
  CSB_Write(device, 14, 0);
  CSB_Write(device, 15, 0);
  CSB_Write(device, 16, 2);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 0);
  CSB_Write(device, 22, 5769216);
  CSB_Write(device, 23, 3670144);
  CSB_Write(device, 24, 2048);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 0);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, 608);
  CSB_Write(device, 30, 608);
  CSB_Write(device, 31, 608);
  CSB_Write(device, 32, 608);
  CSB_Write(device, 33, 15);
  while (CSB_Read(device, 1) != 1) {}
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, 19);
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, 19);
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 2048);
  CSB_Write(device, 9, 0);
  CSB_Write(device, 10, 0);
  CSB_Write(device, 11, 140032);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 277632);
  CSB_Write(device, 14, 0);
  CSB_Write(device, 15, 0);
  CSB_Write(device, 16, 2);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 0);
  CSB_Write(device, 22, 5769216);
  CSB_Write(device, 23, 3670144);
  CSB_Write(device, 24, 2048);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 0);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, 608);
  CSB_Write(device, 30, 608);
  CSB_Write(device, 31, 608);
  CSB_Write(device, 32, 608);
  CSB_Write(device, 33, 15);
  while (CSB_Read(device, 1) != 1) {}
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, 19);
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, 19);
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 3072);
  CSB_Write(device, 9, 0);
  CSB_Write(device, 10, 0);
  CSB_Write(device, 11, 207616);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 278848);
  CSB_Write(device, 14, 0);
  CSB_Write(device, 15, 0);
  CSB_Write(device, 16, 2);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 0);
  CSB_Write(device, 22, 5769216);
  CSB_Write(device, 23, 3670144);
  CSB_Write(device, 24, 2048);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 0);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, 608);
  CSB_Write(device, 30, 608);
  CSB_Write(device, 31, 608);
  CSB_Write(device, 32, 608);
  CSB_Write(device, 33, 15);
  while (CSB_Read(device, 1) != 1) {}
}

void test(HANDLE& device) {
  mvm_step_1(device);
}
